//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TestGrammar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class TestGrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, Inum=30, Fnum=31, Dnum=32, 
		ID=33, WHITESPACE=34, NEWLINE=35;
	public const int
		RULE_prog = 0, RULE_stmts = 1, RULE_stmt = 2, RULE_assignment = 3, RULE_exprs = 4, 
		RULE_expr = 5, RULE_textstring = 6, RULE_selective = 7, RULE_iterative = 8, 
		RULE_bexpr = 9, RULE_print = 10, RULE_dummy = 11, RULE_val = 12, RULE_valtype = 13, 
		RULE_id = 14, RULE_num = 15;
	public static readonly string[] ruleNames = {
		"prog", "stmts", "stmt", "assignment", "exprs", "expr", "textstring", 
		"selective", "iterative", "bexpr", "print", "dummy", "val", "valtype", 
		"id", "num"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'='", "','", "'('", "')'", "'sqrt'", "'%'", "'**'", "'*'", 
		"'/'", "'+'", "'-'", "'++'", "'--'", "'\"'", "'if'", "'{'", "'}'", "'elif'", 
		"'else'", "'for'", "'>'", "'<'", "'!'", "'print'", "'dummy'", "'int'", 
		"'float'", "'double'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "Inum", "Fnum", "Dnum", "ID", "WHITESPACE", 
		"NEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TestGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TestGrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public TestGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public TestGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(TestGrammarParser.Eof, 0); }
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			stmts();
			State = 33;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public StmtsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmts; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterStmts(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitStmts(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmts(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtsContext stmts() {
		StmtsContext _localctx = new StmtsContext(Context, State);
		EnterRule(_localctx, 2, RULE_stmts);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__15) | (1L << T__20) | (1L << T__24) | (1L << T__26) | (1L << T__27) | (1L << T__28) | (1L << ID))) != 0)) {
				{
				State = 35;
				stmt();
				State = 36;
				stmts();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectiveContext selective() {
			return GetRuleContext<SelectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IterativeContext iterative() {
			return GetRuleContext<IterativeContext>(0);
		}
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 4, RULE_stmt);
		try {
			State = 50;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__24:
			case T__26:
			case T__27:
			case T__28:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 42;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__26:
				case T__27:
				case T__28:
				case ID:
					{
					State = 40;
					assignment();
					}
					break;
				case T__24:
					{
					State = 41;
					print();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 44;
				Match(T__0);
				}
				}
				break;
			case T__15:
			case T__20:
				EnterOuterAlt(_localctx, 2);
				{
				State = 48;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__15:
					{
					State = 46;
					selective();
					}
					break;
				case T__20:
					{
					State = 47;
					iterative();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValtypeContext valtype() {
			return GetRuleContext<ValtypeContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 6, RULE_assignment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__26) | (1L << T__27) | (1L << T__28))) != 0)) {
				{
				State = 52;
				valtype();
				}
			}

			State = 55;
			id();
			State = 56;
			Match(T__1);
			State = 57;
			expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprsContext exprs() {
			return GetRuleContext<ExprsContext>(0);
		}
		public ExprsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterExprs(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitExprs(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprsContext exprs() {
		ExprsContext _localctx = new ExprsContext(Context, State);
		EnterRule(_localctx, 8, RULE_exprs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			expr(0);
			State = 62;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 60;
				Match(T__2);
				State = 61;
				exprs();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValContext val() {
			return GetRuleContext<ValContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				State = 65;
				Match(T__3);
				State = 66;
				expr(0);
				State = 67;
				Match(T__4);
				}
				break;
			case T__5:
				{
				State = 69;
				Match(T__5);
				State = 70;
				expr(7);
				}
				break;
			case T__10:
			case T__11:
			case Inum:
			case Fnum:
			case Dnum:
			case ID:
				{
				State = 71;
				val();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 89;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 87;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
					case 1:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 74;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 75;
						_la = TokenStream.LA(1);
						if ( !(_la==T__6 || _la==T__7) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 76;
						expr(7);
						}
						break;
					case 2:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 77;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 78;
						_la = TokenStream.LA(1);
						if ( !(_la==T__8 || _la==T__9) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 79;
						expr(6);
						}
						break;
					case 3:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 80;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 81;
						_la = TokenStream.LA(1);
						if ( !(_la==T__10 || _la==T__11) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 82;
						expr(5);
						}
						break;
					case 4:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 83;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 84;
						Match(T__12);
						}
						break;
					case 5:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 85;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 86;
						Match(T__13);
						}
						break;
					}
					} 
				}
				State = 91;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TextstringContext : ParserRuleContext {
		public TextstringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textstring; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterTextstring(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitTextstring(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextstring(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextstringContext textstring() {
		TextstringContext _localctx = new TextstringContext(Context, State);
		EnterRule(_localctx, 12, RULE_textstring);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(T__14);
			State = 96;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 93;
					MatchWildcard();
					}
					} 
				}
				State = 98;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			State = 99;
			Match(T__14);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtsContext[] stmts() {
			return GetRuleContexts<StmtsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtsContext stmts(int i) {
			return GetRuleContext<StmtsContext>(i);
		}
		public SelectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selective; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterSelective(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitSelective(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectiveContext selective() {
		SelectiveContext _localctx = new SelectiveContext(Context, State);
		EnterRule(_localctx, 14, RULE_selective);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			Match(T__15);
			State = 102;
			Match(T__3);
			State = 103;
			bexpr(0);
			State = 104;
			Match(T__4);
			State = 105;
			Match(T__16);
			State = 106;
			stmts();
			State = 107;
			Match(T__17);
			State = 118;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__18) {
				{
				{
				State = 108;
				Match(T__18);
				State = 109;
				Match(T__3);
				State = 110;
				bexpr(0);
				State = 111;
				Match(T__4);
				State = 112;
				Match(T__16);
				State = 113;
				stmts();
				State = 114;
				Match(T__17);
				}
				}
				State = 120;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 126;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__19) {
				{
				State = 121;
				Match(T__19);
				State = 122;
				Match(T__16);
				State = 123;
				stmts();
				State = 124;
				Match(T__17);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IterativeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprsContext exprs() {
			return GetRuleContext<ExprsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public IterativeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iterative; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterIterative(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitIterative(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIterative(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IterativeContext iterative() {
		IterativeContext _localctx = new IterativeContext(Context, State);
		EnterRule(_localctx, 16, RULE_iterative);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			Match(T__20);
			State = 129;
			Match(T__3);
			State = 130;
			assignment();
			State = 131;
			Match(T__0);
			State = 132;
			bexpr(0);
			State = 133;
			Match(T__0);
			State = 134;
			exprs();
			State = 135;
			Match(T__4);
			State = 136;
			Match(T__16);
			State = 137;
			stmts();
			State = 138;
			Match(T__17);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BexprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public BexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bexpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterBexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitBexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BexprContext bexpr() {
		return bexpr(0);
	}

	private BexprContext bexpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BexprContext _localctx = new BexprContext(Context, _parentState);
		BexprContext _prevctx = _localctx;
		int _startState = 18;
		EnterRecursionRule(_localctx, 18, RULE_bexpr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 150;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 142;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__23) {
					{
					State = 141;
					Match(T__23);
					}
				}

				State = 144;
				expr(0);
				}
				break;
			case 2:
				{
				State = 145;
				Match(T__23);
				State = 146;
				Match(T__3);
				State = 147;
				bexpr(0);
				State = 148;
				Match(T__4);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 164;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 162;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
					case 1:
						{
						_localctx = new BexprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 152;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 153;
						_la = TokenStream.LA(1);
						if ( !(_la==T__21 || _la==T__22) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 155;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if (_la==T__1) {
							{
							State = 154;
							Match(T__1);
							}
						}

						State = 157;
						bexpr(5);
						}
						break;
					case 2:
						{
						_localctx = new BexprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 158;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 159;
						_la = TokenStream.LA(1);
						if ( !(_la==T__1 || _la==T__23) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 160;
						Match(T__1);
						State = 161;
						bexpr(4);
						}
						break;
					}
					} 
				}
				State = 166;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextstringContext textstring() {
			return GetRuleContext<TextstringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 20, RULE_print);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			Match(T__24);
			State = 170;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__14:
				{
				State = 168;
				textstring();
				}
				break;
			case T__3:
			case T__5:
			case T__10:
			case T__11:
			case T__23:
			case Inum:
			case Fnum:
			case Dnum:
			case ID:
				{
				State = 169;
				bexpr(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DummyContext : ParserRuleContext {
		public DummyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dummy; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterDummy(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitDummy(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDummy(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DummyContext dummy() {
		DummyContext _localctx = new DummyContext(Context, State);
		EnterRule(_localctx, 22, RULE_dummy);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 172;
			Match(T__25);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		public ValContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_val; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterVal(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitVal(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVal(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValContext val() {
		ValContext _localctx = new ValContext(Context, State);
		EnterRule(_localctx, 24, RULE_val);
		int _la;
		try {
			State = 182;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 174;
				id();
				}
				break;
			case T__10:
			case T__11:
			case Inum:
			case Fnum:
			case Dnum:
				EnterOuterAlt(_localctx, 2);
				{
				State = 179;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__10:
					{
					State = 175;
					Match(T__10);
					}
					break;
				case T__11:
				case Inum:
				case Fnum:
				case Dnum:
					{
					State = 177;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==T__11) {
						{
						State = 176;
						Match(T__11);
						}
					}

					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 181;
				num();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValtypeContext : ParserRuleContext {
		public ValtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_valtype; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterValtype(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitValtype(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValtype(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValtypeContext valtype() {
		ValtypeContext _localctx = new ValtypeContext(Context, State);
		EnterRule(_localctx, 26, RULE_valtype);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__26) | (1L << T__27) | (1L << T__28))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(TestGrammarParser.ID, 0); }
		public IdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitId(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdContext id() {
		IdContext _localctx = new IdContext(Context, State);
		EnterRule(_localctx, 28, RULE_id);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Inum() { return GetToken(TestGrammarParser.Inum, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Fnum() { return GetToken(TestGrammarParser.Fnum, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dnum() { return GetToken(TestGrammarParser.Dnum, 0); }
		public NumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.EnterNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestGrammarListener typedListener = listener as ITestGrammarListener;
			if (typedListener != null) typedListener.ExitNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestGrammarVisitor<TResult> typedVisitor = visitor as ITestGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumContext num() {
		NumContext _localctx = new NumContext(Context, State);
		EnterRule(_localctx, 30, RULE_num);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Inum) | (1L << Fnum) | (1L << Dnum))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return expr_sempred((ExprContext)_localctx, predIndex);
		case 9: return bexpr_sempred((BexprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 6);
		case 1: return Precpred(Context, 5);
		case 2: return Precpred(Context, 4);
		case 3: return Precpred(Context, 3);
		case 4: return Precpred(Context, 2);
		}
		return true;
	}
	private bool bexpr_sempred(BexprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 5: return Precpred(Context, 4);
		case 6: return Precpred(Context, 3);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '%', '\xC1', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', ')', '\n', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x5', '\x4', '-', '\n', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '\x33', '\n', '\x4', 
		'\x5', '\x4', '\x35', '\n', '\x4', '\x3', '\x5', '\x5', '\x5', '\x38', 
		'\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x41', '\n', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 'K', '\n', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\a', '\a', 'Z', '\n', '\a', '\f', '\a', '\xE', '\a', ']', 
		'\v', '\a', '\x3', '\b', '\x3', '\b', '\a', '\b', '\x61', '\n', '\b', 
		'\f', '\b', '\xE', '\b', '\x64', '\v', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', '\t', 'w', '\n', 
		'\t', '\f', '\t', '\xE', '\t', 'z', '\v', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x81', '\n', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\x91', '\n', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x5', '\v', '\x99', '\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x5', '\v', '\x9E', '\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\a', '\v', '\xA5', '\n', '\v', '\f', 
		'\v', '\xE', '\v', '\xA8', '\v', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x5', '\f', '\xAD', '\n', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\xB4', '\n', '\xE', 
		'\x5', '\xE', '\xB6', '\n', '\xE', '\x3', '\xE', '\x5', '\xE', '\xB9', 
		'\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x62', '\x4', '\f', 
		'\x14', '\x12', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\x2', '\t', 
		'\x3', '\x2', '\t', '\n', '\x3', '\x2', '\v', '\f', '\x3', '\x2', '\r', 
		'\xE', '\x3', '\x2', '\x18', '\x19', '\x4', '\x2', '\x4', '\x4', '\x1A', 
		'\x1A', '\x3', '\x2', '\x1D', '\x1F', '\x3', '\x2', ' ', '\"', '\x2', 
		'\xC9', '\x2', '\"', '\x3', '\x2', '\x2', '\x2', '\x4', '(', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '\x34', '\x3', '\x2', '\x2', '\x2', '\b', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\n', '=', '\x3', '\x2', '\x2', '\x2', '\f', 
		'J', '\x3', '\x2', '\x2', '\x2', '\xE', '^', '\x3', '\x2', '\x2', '\x2', 
		'\x10', 'g', '\x3', '\x2', '\x2', '\x2', '\x12', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\x98', '\x3', '\x2', '\x2', '\x2', '\x16', '\xA9', 
		'\x3', '\x2', '\x2', '\x2', '\x18', '\xAE', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '\xB8', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xBA', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\xBC', '\x3', '\x2', '\x2', '\x2', ' ', '\xBE', 
		'\x3', '\x2', '\x2', '\x2', '\"', '#', '\x5', '\x4', '\x3', '\x2', '#', 
		'$', '\a', '\x2', '\x2', '\x3', '$', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'%', '&', '\x5', '\x6', '\x4', '\x2', '&', '\'', '\x5', '\x4', '\x3', 
		'\x2', '\'', ')', '\x3', '\x2', '\x2', '\x2', '(', '%', '\x3', '\x2', 
		'\x2', '\x2', '(', ')', '\x3', '\x2', '\x2', '\x2', ')', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '*', '-', '\x5', '\b', '\x5', '\x2', '+', '-', '\x5', 
		'\x16', '\f', '\x2', ',', '*', '\x3', '\x2', '\x2', '\x2', ',', '+', '\x3', 
		'\x2', '\x2', '\x2', '-', '.', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', 
		'\x3', '\x2', '\x2', '/', '\x35', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\x33', '\x5', '\x10', '\t', '\x2', '\x31', '\x33', '\x5', '\x12', '\n', 
		'\x2', '\x32', '\x30', '\x3', '\x2', '\x2', '\x2', '\x32', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x35', '\x3', '\x2', '\x2', '\x2', '\x34', 
		',', '\x3', '\x2', '\x2', '\x2', '\x34', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\a', '\x3', '\x2', '\x2', '\x2', '\x36', '\x38', '\x5', 
		'\x1C', '\xF', '\x2', '\x37', '\x36', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ':', '\x5', '\x1E', '\x10', '\x2', ':', ';', '\a', '\x4', 
		'\x2', '\x2', ';', '<', '\x5', '\f', '\a', '\x2', '<', '\t', '\x3', '\x2', 
		'\x2', '\x2', '=', '@', '\x5', '\f', '\a', '\x2', '>', '?', '\a', '\x5', 
		'\x2', '\x2', '?', '\x41', '\x5', '\n', '\x6', '\x2', '@', '>', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\v', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\b', '\a', '\x1', '\x2', 
		'\x43', '\x44', '\a', '\x6', '\x2', '\x2', '\x44', '\x45', '\x5', '\f', 
		'\a', '\x2', '\x45', '\x46', '\a', '\a', '\x2', '\x2', '\x46', 'K', '\x3', 
		'\x2', '\x2', '\x2', 'G', 'H', '\a', '\b', '\x2', '\x2', 'H', 'K', '\x5', 
		'\f', '\a', '\t', 'I', 'K', '\x5', '\x1A', '\xE', '\x2', 'J', '\x42', 
		'\x3', '\x2', '\x2', '\x2', 'J', 'G', '\x3', '\x2', '\x2', '\x2', 'J', 
		'I', '\x3', '\x2', '\x2', '\x2', 'K', '[', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\f', '\b', '\x2', '\x2', 'M', 'N', '\t', '\x2', '\x2', '\x2', 
		'N', 'Z', '\x5', '\f', '\a', '\t', 'O', 'P', '\f', '\a', '\x2', '\x2', 
		'P', 'Q', '\t', '\x3', '\x2', '\x2', 'Q', 'Z', '\x5', '\f', '\a', '\b', 
		'R', 'S', '\f', '\x6', '\x2', '\x2', 'S', 'T', '\t', '\x4', '\x2', '\x2', 
		'T', 'Z', '\x5', '\f', '\a', '\a', 'U', 'V', '\f', '\x5', '\x2', '\x2', 
		'V', 'Z', '\a', '\xF', '\x2', '\x2', 'W', 'X', '\f', '\x4', '\x2', '\x2', 
		'X', 'Z', '\a', '\x10', '\x2', '\x2', 'Y', 'L', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'O', '\x3', '\x2', '\x2', '\x2', 'Y', 'R', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'U', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 
		'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '\r', '\x3', '\x2', '\x2', 
		'\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', '\x62', '\a', '\x11', 
		'\x2', '\x2', '_', '\x61', '\v', '\x2', '\x2', '\x2', '`', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x64', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x62', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x65', '\x3', '\x2', '\x2', '\x2', '\x64', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x66', '\a', '\x11', '\x2', '\x2', '\x66', 
		'\xF', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '\x12', '\x2', '\x2', 
		'h', 'i', '\a', '\x6', '\x2', '\x2', 'i', 'j', '\x5', '\x14', '\v', '\x2', 
		'j', 'k', '\a', '\a', '\x2', '\x2', 'k', 'l', '\a', '\x13', '\x2', '\x2', 
		'l', 'm', '\x5', '\x4', '\x3', '\x2', 'm', 'x', '\a', '\x14', '\x2', '\x2', 
		'n', 'o', '\a', '\x15', '\x2', '\x2', 'o', 'p', '\a', '\x6', '\x2', '\x2', 
		'p', 'q', '\x5', '\x14', '\v', '\x2', 'q', 'r', '\a', '\a', '\x2', '\x2', 
		'r', 's', '\a', '\x13', '\x2', '\x2', 's', 't', '\x5', '\x4', '\x3', '\x2', 
		't', 'u', '\a', '\x14', '\x2', '\x2', 'u', 'w', '\x3', '\x2', '\x2', '\x2', 
		'v', 'n', '\x3', '\x2', '\x2', '\x2', 'w', 'z', '\x3', '\x2', '\x2', '\x2', 
		'x', 'v', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x3', '\x2', '\x2', '\x2', 
		'y', '\x80', '\x3', '\x2', '\x2', '\x2', 'z', 'x', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '\x16', '\x2', '\x2', '|', '}', '\a', '\x13', '\x2', 
		'\x2', '}', '~', '\x5', '\x4', '\x3', '\x2', '~', '\x7F', '\a', '\x14', 
		'\x2', '\x2', '\x7F', '\x81', '\x3', '\x2', '\x2', '\x2', '\x80', '{', 
		'\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x11', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', '\x17', 
		'\x2', '\x2', '\x83', '\x84', '\a', '\x6', '\x2', '\x2', '\x84', '\x85', 
		'\x5', '\b', '\x5', '\x2', '\x85', '\x86', '\a', '\x3', '\x2', '\x2', 
		'\x86', '\x87', '\x5', '\x14', '\v', '\x2', '\x87', '\x88', '\a', '\x3', 
		'\x2', '\x2', '\x88', '\x89', '\x5', '\n', '\x6', '\x2', '\x89', '\x8A', 
		'\a', '\a', '\x2', '\x2', '\x8A', '\x8B', '\a', '\x13', '\x2', '\x2', 
		'\x8B', '\x8C', '\x5', '\x4', '\x3', '\x2', '\x8C', '\x8D', '\a', '\x14', 
		'\x2', '\x2', '\x8D', '\x13', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x90', 
		'\b', '\v', '\x1', '\x2', '\x8F', '\x91', '\a', '\x1A', '\x2', '\x2', 
		'\x90', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x92', '\x99', 
		'\x5', '\f', '\a', '\x2', '\x93', '\x94', '\a', '\x1A', '\x2', '\x2', 
		'\x94', '\x95', '\a', '\x6', '\x2', '\x2', '\x95', '\x96', '\x5', '\x14', 
		'\v', '\x2', '\x96', '\x97', '\a', '\a', '\x2', '\x2', '\x97', '\x99', 
		'\x3', '\x2', '\x2', '\x2', '\x98', '\x8E', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x93', '\x3', '\x2', '\x2', '\x2', '\x99', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\x9A', '\x9B', '\f', '\x6', '\x2', '\x2', '\x9B', '\x9D', 
		'\t', '\x5', '\x2', '\x2', '\x9C', '\x9E', '\a', '\x4', '\x2', '\x2', 
		'\x9D', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA5', 
		'\x5', '\x14', '\v', '\a', '\xA0', '\xA1', '\f', '\x5', '\x2', '\x2', 
		'\xA1', '\xA2', '\t', '\x6', '\x2', '\x2', '\xA2', '\xA3', '\a', '\x4', 
		'\x2', '\x2', '\xA3', '\xA5', '\x5', '\x14', '\v', '\x6', '\xA4', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', '\xA4', '\xA0', '\x3', '\x2', '\x2', '\x2', 
		'\xA5', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\x15', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\xA9', '\xAC', '\a', '\x1B', '\x2', '\x2', '\xAA', '\xAD', '\x5', '\xE', 
		'\b', '\x2', '\xAB', '\xAD', '\x5', '\x14', '\v', '\x2', '\xAC', '\xAA', 
		'\x3', '\x2', '\x2', '\x2', '\xAC', '\xAB', '\x3', '\x2', '\x2', '\x2', 
		'\xAD', '\x17', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', '\x1C', 
		'\x2', '\x2', '\xAF', '\x19', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB9', 
		'\x5', '\x1E', '\x10', '\x2', '\xB1', '\xB6', '\a', '\r', '\x2', '\x2', 
		'\xB2', '\xB4', '\a', '\xE', '\x2', '\x2', '\xB3', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB6', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB1', '\x3', '\x2', '\x2', '\x2', 
		'\xB5', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '\xB9', '\x5', ' ', '\x11', '\x2', '\xB8', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\xB8', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\t', '\a', 
		'\x2', '\x2', '\xBB', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', 
		'\a', '#', '\x2', '\x2', '\xBD', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xBF', '\t', '\b', '\x2', '\x2', '\xBF', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x17', '(', ',', '\x32', '\x34', '\x37', '@', 'J', 'Y', '[', '\x62', 
		'x', '\x80', '\x90', '\x98', '\x9D', '\xA4', '\xA6', '\xAC', '\xB3', '\xB5', 
		'\xB8',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
