//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TestGrammar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TestGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface ITestGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] TestGrammarParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.stmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmts([NotNull] TestGrammarParser.StmtsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] TestGrammarParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] TestGrammarParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.exprs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprs([NotNull] TestGrammarParser.ExprsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] TestGrammarParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.textstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextstring([NotNull] TestGrammarParser.TextstringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.selective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelective([NotNull] TestGrammarParser.SelectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.iterative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterative([NotNull] TestGrammarParser.IterativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBexpr([NotNull] TestGrammarParser.BexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] TestGrammarParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.dummy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDummy([NotNull] TestGrammarParser.DummyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.val"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVal([NotNull] TestGrammarParser.ValContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.valtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValtype([NotNull] TestGrammarParser.ValtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] TestGrammarParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestGrammarParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum([NotNull] TestGrammarParser.NumContext context);
}
