//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\noobs\Documents\Github\P4-Emotional-Damage\Compiler\EmotionalDamage2\EmotionalDamage.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class EmotionalDamageParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, Inum=45, Fnum=46, 
		IDENTIFIER=47, STRING_CONSTANT=48, WS=49;
	public const int
		RULE_prog = 0, RULE_stmts = 1, RULE_numtype = 2, RULE_print = 3, RULE_types = 4, 
		RULE_returntype = 5, RULE_dcl = 6, RULE_stmt = 7, RULE_ifstmt = 8, RULE_elifstmt = 9, 
		RULE_elsestmt = 10, RULE_expr = 11, RULE_bexpr = 12;
	public static readonly string[] ruleNames = {
		"prog", "stmts", "numtype", "print", "types", "returntype", "dcl", "stmt", 
		"ifstmt", "elifstmt", "elsestmt", "expr", "bexpr"
	};

	private static readonly string[] _LiteralNames = {
		null, "'int'", "'float'", "'print'", "'println'", "'['", "']'", "'bool'", 
		"'string'", "'void'", "'('", "','", "')'", "'{'", "'}'", "';'", "'='", 
		"'return'", "'++'", "'--'", "'T'", "'while'", "'for'", "'if'", "'elif'", 
		"'else'", "'sqrt'", "'**'", "'%'", "'*'", "'/'", "'+'", "'-'", "'\\\\'", 
		"'.row'", "'.col'", "'.len'", "'>'", "'<'", "'>='", "'<='", "'=='", "'!='", 
		"'true'", "'false'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "Inum", "Fnum", 
		"IDENTIFIER", "STRING_CONSTANT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EmotionalDamage.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static EmotionalDamageParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EmotionalDamageParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EmotionalDamageParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(EmotionalDamageParser.Eof, 0); }
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 26; stmts();
			State = 27; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtsContext : ParserRuleContext {
		public DclContext[] dcl() {
			return GetRuleContexts<DclContext>();
		}
		public DclContext dcl(int i) {
			return GetRuleContext<DclContext>(i);
		}
		public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public StmtsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmts; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmts(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtsContext stmts() {
		StmtsContext _localctx = new StmtsContext(Context, State);
		EnterRule(_localctx, 2, RULE_stmts);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 33;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__16) | (1L << T__19) | (1L << T__20) | (1L << T__21) | (1L << T__22) | (1L << IDENTIFIER))) != 0)) {
				{
				State = 31;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__0:
				case T__1:
				case T__6:
				case T__7:
				case T__8:
					{
					State = 29; dcl();
					}
					break;
				case T__2:
				case T__3:
				case T__16:
				case T__19:
				case T__20:
				case T__21:
				case T__22:
				case IDENTIFIER:
					{
					State = 30; stmt();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 35;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumtypeContext : ParserRuleContext {
		public NumtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numtype; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumtype(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumtypeContext numtype() {
		NumtypeContext _localctx = new NumtypeContext(Context, State);
		EnterRule(_localctx, 4, RULE_numtype);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			_la = TokenStream.LA(1);
			if ( !(_la==T__0 || _la==T__1) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 6, RULE_print);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38;
			_la = TokenStream.LA(1);
			if ( !(_la==T__2 || _la==T__3) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypesContext : ParserRuleContext {
		public ITerminalNode[] Inum() { return GetTokens(EmotionalDamageParser.Inum); }
		public ITerminalNode Inum(int i) {
			return GetToken(EmotionalDamageParser.Inum, i);
		}
		public TypesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_types; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypes(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypesContext types() {
		TypesContext _localctx = new TypesContext(Context, State);
		EnterRule(_localctx, 8, RULE_types);
		int _la;
		try {
			State = 64;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 40; Match(T__0);
				State = 44;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
				case 1:
					{
					State = 41; Match(T__4);
					State = 42; Match(Inum);
					State = 43; Match(T__5);
					}
					break;
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__4) {
					{
					State = 46; Match(T__4);
					State = 47; Match(Inum);
					State = 48; Match(T__5);
					}
				}

				}
				break;
			case T__1:
				EnterOuterAlt(_localctx, 2);
				{
				State = 51; Match(T__1);
				State = 55;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
				case 1:
					{
					State = 52; Match(T__4);
					State = 53; Match(Inum);
					State = 54; Match(T__5);
					}
					break;
				}
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__4) {
					{
					State = 57; Match(T__4);
					State = 58; Match(Inum);
					State = 59; Match(T__5);
					}
				}

				}
				break;
			case T__6:
				EnterOuterAlt(_localctx, 3);
				{
				State = 62; Match(T__6);
				}
				break;
			case T__7:
				EnterOuterAlt(_localctx, 4);
				{
				State = 63; Match(T__7);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturntypeContext : ParserRuleContext {
		public TypesContext types() {
			return GetRuleContext<TypesContext>(0);
		}
		public ReturntypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returntype; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturntype(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturntypeContext returntype() {
		ReturntypeContext _localctx = new ReturntypeContext(Context, State);
		EnterRule(_localctx, 10, RULE_returntype);
		try {
			State = 68;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
			case T__1:
			case T__6:
			case T__7:
				EnterOuterAlt(_localctx, 1);
				{
				State = 66; types();
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 67; Match(T__8);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DclContext : ParserRuleContext {
		public DclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dcl; } }
	 
		public DclContext() { }
		public virtual void CopyFrom(DclContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ArrayDeclarationContext : DclContext {
		public ITerminalNode Inum() { return GetToken(EmotionalDamageParser.Inum, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public NumtypeContext numtype() {
			return GetRuleContext<NumtypeContext>(0);
		}
		public ArrayDeclarationContext(DclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringDclContext : DclContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public ITerminalNode STRING_CONSTANT() { return GetToken(EmotionalDamageParser.STRING_CONSTANT, 0); }
		public StringDclContext(DclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringDcl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MatrixDeclarationContext : DclContext {
		public NumtypeContext numtype() {
			return GetRuleContext<NumtypeContext>(0);
		}
		public ITerminalNode[] Inum() { return GetTokens(EmotionalDamageParser.Inum); }
		public ITerminalNode Inum(int i) {
			return GetToken(EmotionalDamageParser.Inum, i);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public MatrixDeclarationContext(DclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMatrixDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumDclContext : DclContext {
		public NumtypeContext numtype() {
			return GetRuleContext<NumtypeContext>(0);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NumDclContext(DclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumDcl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncDclContext : DclContext {
		public ReturntypeContext returntype() {
			return GetRuleContext<ReturntypeContext>(0);
		}
		public ITerminalNode[] IDENTIFIER() { return GetTokens(EmotionalDamageParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(EmotionalDamageParser.IDENTIFIER, i);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public TypesContext[] types() {
			return GetRuleContexts<TypesContext>();
		}
		public TypesContext types(int i) {
			return GetRuleContext<TypesContext>(i);
		}
		public FuncDclContext(DclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncDcl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolDeclarationContext : DclContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public BoolDeclarationContext(DclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DclContext dcl() {
		DclContext _localctx = new DclContext(Context, State);
		EnterRule(_localctx, 12, RULE_dcl);
		int _la;
		try {
			State = 128;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				_localctx = new FuncDclContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 70; returntype();
				State = 71; Match(IDENTIFIER);
				State = 72; Match(T__9);
				State = 85;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__6) | (1L << T__7))) != 0)) {
					{
					{
					State = 73; types();
					State = 74; Match(IDENTIFIER);
					}
					State = 82;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__10) {
						{
						{
						State = 76; Match(T__10);
						State = 77; types();
						State = 78; Match(IDENTIFIER);
						}
						}
						State = 84;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 87; Match(T__11);
				State = 88; Match(T__12);
				State = 89; stmts();
				State = 90; Match(T__13);
				}
				break;
			case 2:
				_localctx = new MatrixDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 92; numtype();
				State = 93; Match(T__4);
				State = 94; Match(Inum);
				State = 95; Match(T__5);
				State = 96; Match(T__4);
				State = 97; Match(Inum);
				State = 98; Match(T__5);
				State = 99; Match(IDENTIFIER);
				State = 100; Match(T__14);
				}
				break;
			case 3:
				_localctx = new ArrayDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 104;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__0:
				case T__1:
					{
					State = 102; numtype();
					}
					break;
				case T__7:
					{
					State = 103; Match(T__7);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 106; Match(T__4);
				State = 107; Match(Inum);
				State = 108; Match(T__5);
				State = 109; Match(IDENTIFIER);
				State = 110; Match(T__14);
				}
				break;
			case 4:
				_localctx = new NumDclContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 111; numtype();
				State = 112; Match(IDENTIFIER);
				State = 113; Match(T__15);
				State = 114; expr(0);
				State = 115; Match(T__14);
				}
				break;
			case 5:
				_localctx = new StringDclContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 117; Match(T__7);
				State = 118; Match(IDENTIFIER);
				State = 119; Match(T__15);
				State = 120; Match(STRING_CONSTANT);
				State = 121; Match(T__14);
				}
				break;
			case 6:
				_localctx = new BoolDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 122; Match(T__6);
				State = 123; Match(IDENTIFIER);
				State = 124; Match(T__15);
				State = 125; bexpr(0);
				State = 126; Match(T__14);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
	 
		public StmtContext() { }
		public virtual void CopyFrom(StmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class UnaryPlusContext : StmtContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public UnaryPlusContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryPlus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusContext : StmtContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public UnaryMinusContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArrayElementAssignStmtContext : StmtContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(EmotionalDamageParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(EmotionalDamageParser.IDENTIFIER, i);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Inum() { return GetToken(EmotionalDamageParser.Inum, 0); }
		public ArrayElementAssignStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayElementAssignStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolAssignStmtContext : StmtContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public BoolAssignStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolAssignStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PrintStmtContext : StmtContext {
		public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		public ITerminalNode STRING_CONSTANT() { return GetToken(EmotionalDamageParser.STRING_CONSTANT, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public PrintStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrintStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncCallContext : StmtContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(EmotionalDamageParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(EmotionalDamageParser.IDENTIFIER, i);
		}
		public FuncCallContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumAssignStmtContext : StmtContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NumAssignStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumAssignStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MatrixElementAssignStmtContext : StmtContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(EmotionalDamageParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(EmotionalDamageParser.IDENTIFIER, i);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode[] Inum() { return GetTokens(EmotionalDamageParser.Inum); }
		public ITerminalNode Inum(int i) {
			return GetToken(EmotionalDamageParser.Inum, i);
		}
		public MatrixElementAssignStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMatrixElementAssignStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhileStmtContext : StmtContext {
		public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public WhileStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhileStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SelectiveContext : StmtContext {
		public IfstmtContext ifstmt() {
			return GetRuleContext<IfstmtContext>(0);
		}
		public ElifstmtContext[] elifstmt() {
			return GetRuleContexts<ElifstmtContext>();
		}
		public ElifstmtContext elifstmt(int i) {
			return GetRuleContext<ElifstmtContext>(i);
		}
		public ElsestmtContext elsestmt() {
			return GetRuleContext<ElsestmtContext>(0);
		}
		public SelectiveContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelective(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ReturnStmtContext : StmtContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public ReturnStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ForStmtContext : StmtContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(EmotionalDamageParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(EmotionalDamageParser.IDENTIFIER, i);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ForStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TransposeMatrixStmtContext : StmtContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public TransposeMatrixStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTransposeMatrixStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 14, RULE_stmt);
		int _la;
		try {
			State = 232;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				_localctx = new PrintStmtContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 130; print();
				State = 131; Match(T__9);
				State = 134;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case STRING_CONSTANT:
					{
					State = 132; Match(STRING_CONSTANT);
					}
					break;
				case T__9:
				case T__25:
				case T__31:
				case Inum:
				case Fnum:
				case IDENTIFIER:
					{
					State = 133; expr(0);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 136; Match(T__11);
				State = 137; Match(T__14);
				}
				break;
			case 2:
				_localctx = new ReturnStmtContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 139; Match(T__16);
				State = 140; Match(IDENTIFIER);
				}
				break;
			case 3:
				_localctx = new NumAssignStmtContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 141; Match(IDENTIFIER);
				State = 142; Match(T__15);
				State = 143; expr(0);
				State = 144; Match(T__14);
				}
				break;
			case 4:
				_localctx = new BoolAssignStmtContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 146; Match(IDENTIFIER);
				State = 147; Match(T__15);
				State = 148; bexpr(0);
				State = 149; Match(T__14);
				}
				break;
			case 5:
				_localctx = new MatrixElementAssignStmtContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 151; Match(IDENTIFIER);
				State = 152; Match(T__4);
				State = 153;
				_la = TokenStream.LA(1);
				if ( !(_la==Inum || _la==IDENTIFIER) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 154; Match(T__5);
				State = 155; Match(T__4);
				State = 156;
				_la = TokenStream.LA(1);
				if ( !(_la==Inum || _la==IDENTIFIER) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 157; Match(T__5);
				State = 158; Match(T__15);
				State = 159; expr(0);
				State = 160; Match(T__14);
				}
				break;
			case 6:
				_localctx = new ArrayElementAssignStmtContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 162; Match(IDENTIFIER);
				State = 163; Match(T__4);
				State = 164;
				_la = TokenStream.LA(1);
				if ( !(_la==Inum || _la==IDENTIFIER) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 165; Match(T__5);
				State = 166; Match(T__15);
				State = 167; expr(0);
				State = 168; Match(T__14);
				}
				break;
			case 7:
				_localctx = new UnaryPlusContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 170; Match(IDENTIFIER);
				State = 171; Match(T__17);
				State = 172; Match(T__14);
				}
				break;
			case 8:
				_localctx = new UnaryMinusContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 173; Match(IDENTIFIER);
				State = 174; Match(T__18);
				State = 175; Match(T__14);
				}
				break;
			case 9:
				_localctx = new TransposeMatrixStmtContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 176; Match(T__19);
				State = 177; Match(T__9);
				State = 178; Match(IDENTIFIER);
				State = 179; Match(T__11);
				State = 180; Match(T__14);
				}
				break;
			case 10:
				_localctx = new WhileStmtContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 181; Match(T__20);
				State = 182; Match(T__9);
				State = 183; bexpr(0);
				State = 184; Match(T__11);
				State = 185; Match(T__12);
				State = 186; stmts();
				State = 187; Match(T__13);
				}
				break;
			case 11:
				_localctx = new ForStmtContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 189; Match(T__21);
				State = 190; Match(T__9);
				State = 191; Match(T__0);
				State = 192; Match(IDENTIFIER);
				State = 193; Match(T__15);
				State = 194; expr(0);
				State = 195; Match(T__14);
				State = 196; bexpr(0);
				State = 197; Match(T__14);
				State = 202;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
				case 1:
					{
					State = 198; Match(IDENTIFIER);
					State = 199; Match(T__17);
					}
					break;
				case 2:
					{
					State = 200; Match(IDENTIFIER);
					State = 201; Match(T__18);
					}
					break;
				}
				State = 204; Match(T__11);
				State = 205; Match(T__12);
				State = 206; stmts();
				State = 207; Match(T__13);
				}
				break;
			case 12:
				_localctx = new FuncCallContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 209; Match(IDENTIFIER);
				State = 210; Match(T__9);
				State = 219;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==IDENTIFIER) {
					{
					State = 211; Match(IDENTIFIER);
					State = 216;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__10) {
						{
						{
						State = 212; Match(T__10);
						State = 213; Match(IDENTIFIER);
						}
						}
						State = 218;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 221; Match(T__11);
				}
				break;
			case 13:
				_localctx = new SelectiveContext(_localctx);
				EnterOuterAlt(_localctx, 13);
				{
				State = 222; ifstmt();
				State = 226;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__23) {
					{
					{
					State = 223; elifstmt();
					}
					}
					State = 228;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 230;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__24) {
					{
					State = 229; elsestmt();
					}
				}

				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfstmtContext : ParserRuleContext {
		public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public IfstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifstmt; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfstmtContext ifstmt() {
		IfstmtContext _localctx = new IfstmtContext(Context, State);
		EnterRule(_localctx, 16, RULE_ifstmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 234; Match(T__22);
			State = 235; Match(T__9);
			State = 236; bexpr(0);
			State = 237; Match(T__11);
			State = 238; Match(T__12);
			State = 239; stmts();
			State = 240; Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElifstmtContext : ParserRuleContext {
		public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ElifstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elifstmt; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElifstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElifstmtContext elifstmt() {
		ElifstmtContext _localctx = new ElifstmtContext(Context, State);
		EnterRule(_localctx, 18, RULE_elifstmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 242; Match(T__23);
			State = 243; Match(T__9);
			State = 244; bexpr(0);
			State = 245; Match(T__11);
			State = 246; Match(T__12);
			State = 247; stmts();
			State = 248; Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElsestmtContext : ParserRuleContext {
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ElsestmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elsestmt; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElsestmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElsestmtContext elsestmt() {
		ElsestmtContext _localctx = new ElsestmtContext(Context, State);
		EnterRule(_localctx, 20, RULE_elsestmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250; Match(T__24);
			State = 251; Match(T__12);
			State = 252; stmts();
			State = 253; Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class RowidContext : ExprContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public RowidContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRowid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LengthidContext : ExprContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public LengthidContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLengthid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntValContext : ExprContext {
		public ITerminalNode Inum() { return GetToken(EmotionalDamageParser.Inum, 0); }
		public IntValContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntVal(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PowExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public PowExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPowExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NegValContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NegValContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNegVal(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FloatValContext : ExprContext {
		public ITerminalNode Fnum() { return GetToken(EmotionalDamageParser.Fnum, 0); }
		public FloatValContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFloatVal(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DivideExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public DivideExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDivideExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GradientExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public GradientExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGradientExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PlusExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public PlusExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlusExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumArrMatrixValueContext : ExprContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(EmotionalDamageParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(EmotionalDamageParser.IDENTIFIER, i);
		}
		public ITerminalNode[] Inum() { return GetTokens(EmotionalDamageParser.Inum); }
		public ITerminalNode Inum(int i) {
			return GetToken(EmotionalDamageParser.Inum, i);
		}
		public NumArrMatrixValueContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumArrMatrixValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SqrtExprContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public SqrtExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSqrtExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ModExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ModExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenExprContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ParenExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TimesExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public TimesExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimesExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ColidContext : ExprContext {
		public ITerminalNode IDENTIFIER() { return GetToken(EmotionalDamageParser.IDENTIFIER, 0); }
		public ColidContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MinusExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MinusExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMinusExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 22;
		EnterRecursionRule(_localctx, 22, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				{
				_localctx = new ParenExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 256; Match(T__9);
				State = 257; expr(0);
				State = 258; Match(T__11);
				}
				break;
			case 2:
				{
				_localctx = new SqrtExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 260; Match(T__25);
				State = 261; expr(15);
				}
				break;
			case 3:
				{
				_localctx = new NumArrMatrixValueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 262; Match(IDENTIFIER);
				State = 266;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
				case 1:
					{
					State = 263; Match(T__4);
					State = 264;
					_la = TokenStream.LA(1);
					if ( !(_la==Inum || _la==IDENTIFIER) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 265; Match(T__5);
					}
					break;
				}
				State = 271;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
				case 1:
					{
					State = 268; Match(T__4);
					State = 269;
					_la = TokenStream.LA(1);
					if ( !(_la==Inum || _la==IDENTIFIER) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 270; Match(T__5);
					}
					break;
				}
				}
				break;
			case 4:
				{
				_localctx = new RowidContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 273; Match(IDENTIFIER);
				State = 274; Match(T__33);
				}
				break;
			case 5:
				{
				_localctx = new ColidContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 275; Match(IDENTIFIER);
				State = 276; Match(T__34);
				}
				break;
			case 6:
				{
				_localctx = new LengthidContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 277; Match(IDENTIFIER);
				State = 278; Match(T__35);
				}
				break;
			case 7:
				{
				_localctx = new NegValContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 279; Match(T__31);
				State = 280; expr(3);
				}
				break;
			case 8:
				{
				_localctx = new IntValContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 281; Match(Inum);
				}
				break;
			case 9:
				{
				_localctx = new FloatValContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 282; Match(Fnum);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 308;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 306;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
					case 1:
						{
						_localctx = new PowExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 285;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 286; Match(T__26);
						State = 287; expr(15);
						}
						break;
					case 2:
						{
						_localctx = new ModExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 288;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 289; Match(T__27);
						State = 290; expr(14);
						}
						break;
					case 3:
						{
						_localctx = new TimesExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 291;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 292; Match(T__28);
						State = 293; expr(13);
						}
						break;
					case 4:
						{
						_localctx = new DivideExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 294;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 295; Match(T__29);
						State = 296; expr(12);
						}
						break;
					case 5:
						{
						_localctx = new PlusExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 297;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 298; Match(T__30);
						State = 299; expr(11);
						}
						break;
					case 6:
						{
						_localctx = new MinusExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 300;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 301; Match(T__31);
						State = 302; expr(10);
						}
						break;
					case 7:
						{
						_localctx = new GradientExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 303;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 304; Match(T__32);
						State = 305; expr(9);
						}
						break;
					}
					} 
				}
				State = 310;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class BexprContext : ParserRuleContext {
		public BexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bexpr; } }
	 
		public BexprContext() { }
		public virtual void CopyFrom(BexprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BoolExprContext : BexprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public BoolExprContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EqualsContext : BexprContext {
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public EqualsContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEquals(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GreaterEqualsContext : BexprContext {
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public GreaterEqualsContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGreaterEquals(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolValueContext : BexprContext {
		public BoolValueContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SmallerEqualsContext : BexprContext {
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public SmallerEqualsContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSmallerEquals(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GreaterContext : BexprContext {
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public GreaterContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGreater(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SmallerContext : BexprContext {
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public SmallerContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSmaller(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NotEqualsContext : BexprContext {
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public NotEqualsContext(BexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEmotionalDamageVisitor<TResult> typedVisitor = visitor as IEmotionalDamageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotEquals(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BexprContext bexpr() {
		return bexpr(0);
	}

	private BexprContext bexpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BexprContext _localctx = new BexprContext(Context, _parentState);
		BexprContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_bexpr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 314;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__42:
			case T__43:
				{
				_localctx = new BoolValueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 312;
				_la = TokenStream.LA(1);
				if ( !(_la==T__42 || _la==T__43) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case T__9:
			case T__25:
			case T__31:
			case Inum:
			case Fnum:
			case IDENTIFIER:
				{
				_localctx = new BoolExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 313; expr(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 336;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 334;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
					case 1:
						{
						_localctx = new GreaterContext(new BexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 316;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 317; Match(T__36);
						State = 318; bexpr(9);
						}
						break;
					case 2:
						{
						_localctx = new SmallerContext(new BexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 319;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 320; Match(T__37);
						State = 321; bexpr(8);
						}
						break;
					case 3:
						{
						_localctx = new GreaterEqualsContext(new BexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 322;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 323; Match(T__38);
						State = 324; bexpr(7);
						}
						break;
					case 4:
						{
						_localctx = new SmallerEqualsContext(new BexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 325;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 326; Match(T__39);
						State = 327; bexpr(6);
						}
						break;
					case 5:
						{
						_localctx = new EqualsContext(new BexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 328;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 329; Match(T__40);
						State = 330; bexpr(5);
						}
						break;
					case 6:
						{
						_localctx = new NotEqualsContext(new BexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 331;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 332; Match(T__41);
						State = 333; bexpr(4);
						}
						break;
					}
					} 
				}
				State = 338;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 11: return expr_sempred((ExprContext)_localctx, predIndex);
		case 12: return bexpr_sempred((BexprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 14);
		case 1: return Precpred(Context, 13);
		case 2: return Precpred(Context, 12);
		case 3: return Precpred(Context, 11);
		case 4: return Precpred(Context, 10);
		case 5: return Precpred(Context, 9);
		case 6: return Precpred(Context, 8);
		}
		return true;
	}
	private bool bexpr_sempred(BexprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 7: return Precpred(Context, 8);
		case 8: return Precpred(Context, 7);
		case 9: return Precpred(Context, 6);
		case 10: return Precpred(Context, 5);
		case 11: return Precpred(Context, 4);
		case 12: return Precpred(Context, 3);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x33', '\x156', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\a', '\x3', '\"', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '%', 
		'\v', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '/', '\n', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x34', 
		'\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', 
		'\x6', ':', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', 
		'\x6', '?', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x43', 
		'\n', '\x6', '\x3', '\a', '\x3', '\a', '\x5', '\a', 'G', '\n', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', '\b', 'S', '\n', 
		'\b', '\f', '\b', '\xE', '\b', 'V', '\v', '\b', '\x5', '\b', 'X', '\n', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x5', '\b', 'k', '\n', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x83', '\n', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x89', 
		'\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x5', '\t', '\xCD', '\n', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\a', '\t', '\xD9', '\n', '\t', '\f', 
		'\t', '\xE', '\t', '\xDC', '\v', '\t', '\x5', '\t', '\xDE', '\n', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', '\t', '\xE3', '\n', '\t', 
		'\f', '\t', '\xE', '\t', '\xE6', '\v', '\t', '\x3', '\t', '\x5', '\t', 
		'\xE9', '\n', '\t', '\x5', '\t', '\xEB', '\n', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\x10D', '\n', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\x112', '\n', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', 
		'\x11E', '\n', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\a', '\r', '\x135', '\n', '\r', '\f', '\r', '\xE', '\r', '\x138', 
		'\v', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\x13D', 
		'\n', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\x151', 
		'\n', '\xE', '\f', '\xE', '\xE', '\xE', '\x154', '\v', '\xE', '\x3', '\xE', 
		'\x2', '\x4', '\x18', '\x1A', '\xF', '\x2', '\x4', '\x6', '\b', '\n', 
		'\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x2', '\x6', 
		'\x3', '\x2', '\x3', '\x4', '\x3', '\x2', '\x5', '\x6', '\x4', '\x2', 
		'/', '/', '\x31', '\x31', '\x3', '\x2', '-', '.', '\x2', '\x184', '\x2', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x4', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x6', '&', '\x3', '\x2', '\x2', '\x2', '\b', '(', '\x3', '\x2', '\x2', 
		'\x2', '\n', '\x42', '\x3', '\x2', '\x2', '\x2', '\f', '\x46', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\x82', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\xEA', '\x3', '\x2', '\x2', '\x2', '\x12', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', '\x14', '\xF4', '\x3', '\x2', '\x2', '\x2', '\x16', '\xFC', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '\x11D', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x13C', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\x5', '\x4', '\x3', 
		'\x2', '\x1D', '\x1E', '\a', '\x2', '\x2', '\x3', '\x1E', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\"', '\x5', '\xE', '\b', '\x2', ' ', '\"', 
		'\x5', '\x10', '\t', '\x2', '!', '\x1F', '\x3', '\x2', '\x2', '\x2', '!', 
		' ', '\x3', '\x2', '\x2', '\x2', '\"', '%', '\x3', '\x2', '\x2', '\x2', 
		'#', '!', '\x3', '\x2', '\x2', '\x2', '#', '$', '\x3', '\x2', '\x2', '\x2', 
		'$', '\x5', '\x3', '\x2', '\x2', '\x2', '%', '#', '\x3', '\x2', '\x2', 
		'\x2', '&', '\'', '\t', '\x2', '\x2', '\x2', '\'', '\a', '\x3', '\x2', 
		'\x2', '\x2', '(', ')', '\t', '\x3', '\x2', '\x2', ')', '\t', '\x3', '\x2', 
		'\x2', '\x2', '*', '.', '\a', '\x3', '\x2', '\x2', '+', ',', '\a', '\a', 
		'\x2', '\x2', ',', '-', '\a', '/', '\x2', '\x2', '-', '/', '\a', '\b', 
		'\x2', '\x2', '.', '+', '\x3', '\x2', '\x2', '\x2', '.', '/', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x33', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', 
		'\a', '\a', '\x2', '\x2', '\x31', '\x32', '\a', '/', '\x2', '\x2', '\x32', 
		'\x34', '\a', '\b', '\x2', '\x2', '\x33', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x39', '\a', '\x4', '\x2', '\x2', '\x36', 
		'\x37', '\a', '\a', '\x2', '\x2', '\x37', '\x38', '\a', '/', '\x2', '\x2', 
		'\x38', ':', '\a', '\b', '\x2', '\x2', '\x39', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ':', '\x3', '\x2', '\x2', '\x2', ':', '>', '\x3', '\x2', 
		'\x2', '\x2', ';', '<', '\a', '\a', '\x2', '\x2', '<', '=', '\a', '/', 
		'\x2', '\x2', '=', '?', '\a', '\b', '\x2', '\x2', '>', ';', '\x3', '\x2', 
		'\x2', '\x2', '>', '?', '\x3', '\x2', '\x2', '\x2', '?', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x43', '\a', '\t', '\x2', '\x2', '\x41', '\x43', 
		'\a', '\n', '\x2', '\x2', '\x42', '*', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x44', 'G', '\x5', '\n', '\x6', '\x2', '\x45', 'G', 
		'\a', '\v', '\x2', '\x2', '\x46', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x46', '\x45', '\x3', '\x2', '\x2', '\x2', 'G', '\r', '\x3', '\x2', '\x2', 
		'\x2', 'H', 'I', '\x5', '\f', '\a', '\x2', 'I', 'J', '\a', '\x31', '\x2', 
		'\x2', 'J', 'W', '\a', '\f', '\x2', '\x2', 'K', 'L', '\x5', '\n', '\x6', 
		'\x2', 'L', 'M', '\a', '\x31', '\x2', '\x2', 'M', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'O', '\a', '\r', '\x2', '\x2', 'O', 'P', '\x5', '\n', '\x6', 
		'\x2', 'P', 'Q', '\a', '\x31', '\x2', '\x2', 'Q', 'S', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'N', '\x3', '\x2', '\x2', '\x2', 'S', 'V', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'X', '\x3', '\x2', '\x2', '\x2', 'V', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'K', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', '\xE', '\x2', 
		'\x2', 'Z', '[', '\a', '\xF', '\x2', '\x2', '[', '\\', '\x5', '\x4', '\x3', 
		'\x2', '\\', ']', '\a', '\x10', '\x2', '\x2', ']', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '^', '_', '\x5', '\x6', '\x4', '\x2', '_', '`', '\a', '\a', 
		'\x2', '\x2', '`', '\x61', '\a', '/', '\x2', '\x2', '\x61', '\x62', '\a', 
		'\b', '\x2', '\x2', '\x62', '\x63', '\a', '\a', '\x2', '\x2', '\x63', 
		'\x64', '\a', '/', '\x2', '\x2', '\x64', '\x65', '\a', '\b', '\x2', '\x2', 
		'\x65', '\x66', '\a', '\x31', '\x2', '\x2', '\x66', 'g', '\a', '\x11', 
		'\x2', '\x2', 'g', '\x83', '\x3', '\x2', '\x2', '\x2', 'h', 'k', '\x5', 
		'\x6', '\x4', '\x2', 'i', 'k', '\a', '\n', '\x2', '\x2', 'j', 'h', '\x3', 
		'\x2', '\x2', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\x3', 
		'\x2', '\x2', '\x2', 'l', 'm', '\a', '\a', '\x2', '\x2', 'm', 'n', '\a', 
		'/', '\x2', '\x2', 'n', 'o', '\a', '\b', '\x2', '\x2', 'o', 'p', '\a', 
		'\x31', '\x2', '\x2', 'p', '\x83', '\a', '\x11', '\x2', '\x2', 'q', 'r', 
		'\x5', '\x6', '\x4', '\x2', 'r', 's', '\a', '\x31', '\x2', '\x2', 's', 
		't', '\a', '\x12', '\x2', '\x2', 't', 'u', '\x5', '\x18', '\r', '\x2', 
		'u', 'v', '\a', '\x11', '\x2', '\x2', 'v', '\x83', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\a', '\n', '\x2', '\x2', 'x', 'y', '\a', '\x31', '\x2', 
		'\x2', 'y', 'z', '\a', '\x12', '\x2', '\x2', 'z', '{', '\a', '\x32', '\x2', 
		'\x2', '{', '\x83', '\a', '\x11', '\x2', '\x2', '|', '}', '\a', '\t', 
		'\x2', '\x2', '}', '~', '\a', '\x31', '\x2', '\x2', '~', '\x7F', '\a', 
		'\x12', '\x2', '\x2', '\x7F', '\x80', '\x5', '\x1A', '\xE', '\x2', '\x80', 
		'\x81', '\a', '\x11', '\x2', '\x2', '\x81', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x82', 'H', '\x3', '\x2', '\x2', '\x2', '\x82', '^', '\x3', '\x2', 
		'\x2', '\x2', '\x82', 'j', '\x3', '\x2', '\x2', '\x2', '\x82', 'q', '\x3', 
		'\x2', '\x2', '\x2', '\x82', 'w', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'|', '\x3', '\x2', '\x2', '\x2', '\x83', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x84', '\x85', '\x5', '\b', '\x5', '\x2', '\x85', '\x88', '\a', '\f', 
		'\x2', '\x2', '\x86', '\x89', '\a', '\x32', '\x2', '\x2', '\x87', '\x89', 
		'\x5', '\x18', '\r', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x88', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '\x8A', '\x8B', '\a', '\xE', '\x2', '\x2', '\x8B', '\x8C', 
		'\a', '\x11', '\x2', '\x2', '\x8C', '\xEB', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '\x8E', '\a', '\x13', '\x2', '\x2', '\x8E', '\xEB', '\a', '\x31', 
		'\x2', '\x2', '\x8F', '\x90', '\a', '\x31', '\x2', '\x2', '\x90', '\x91', 
		'\a', '\x12', '\x2', '\x2', '\x91', '\x92', '\x5', '\x18', '\r', '\x2', 
		'\x92', '\x93', '\a', '\x11', '\x2', '\x2', '\x93', '\xEB', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x95', '\a', '\x31', '\x2', '\x2', '\x95', '\x96', 
		'\a', '\x12', '\x2', '\x2', '\x96', '\x97', '\x5', '\x1A', '\xE', '\x2', 
		'\x97', '\x98', '\a', '\x11', '\x2', '\x2', '\x98', '\xEB', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '\x9A', '\a', '\x31', '\x2', '\x2', '\x9A', '\x9B', 
		'\a', '\a', '\x2', '\x2', '\x9B', '\x9C', '\t', '\x4', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', '\b', '\x2', '\x2', '\x9D', '\x9E', '\a', '\a', '\x2', '\x2', 
		'\x9E', '\x9F', '\t', '\x4', '\x2', '\x2', '\x9F', '\xA0', '\a', '\b', 
		'\x2', '\x2', '\xA0', '\xA1', '\a', '\x12', '\x2', '\x2', '\xA1', '\xA2', 
		'\x5', '\x18', '\r', '\x2', '\xA2', '\xA3', '\a', '\x11', '\x2', '\x2', 
		'\xA3', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', '\x31', 
		'\x2', '\x2', '\xA5', '\xA6', '\a', '\a', '\x2', '\x2', '\xA6', '\xA7', 
		'\t', '\x4', '\x2', '\x2', '\xA7', '\xA8', '\a', '\b', '\x2', '\x2', '\xA8', 
		'\xA9', '\a', '\x12', '\x2', '\x2', '\xA9', '\xAA', '\x5', '\x18', '\r', 
		'\x2', '\xAA', '\xAB', '\a', '\x11', '\x2', '\x2', '\xAB', '\xEB', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', '\x31', '\x2', '\x2', '\xAD', 
		'\xAE', '\a', '\x14', '\x2', '\x2', '\xAE', '\xEB', '\a', '\x11', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', '\x31', '\x2', '\x2', '\xB0', '\xB1', '\a', 
		'\x15', '\x2', '\x2', '\xB1', '\xEB', '\a', '\x11', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', '\x16', '\x2', '\x2', '\xB3', '\xB4', '\a', '\f', '\x2', 
		'\x2', '\xB4', '\xB5', '\a', '\x31', '\x2', '\x2', '\xB5', '\xB6', '\a', 
		'\xE', '\x2', '\x2', '\xB6', '\xEB', '\a', '\x11', '\x2', '\x2', '\xB7', 
		'\xB8', '\a', '\x17', '\x2', '\x2', '\xB8', '\xB9', '\a', '\f', '\x2', 
		'\x2', '\xB9', '\xBA', '\x5', '\x1A', '\xE', '\x2', '\xBA', '\xBB', '\a', 
		'\xE', '\x2', '\x2', '\xBB', '\xBC', '\a', '\xF', '\x2', '\x2', '\xBC', 
		'\xBD', '\x5', '\x4', '\x3', '\x2', '\xBD', '\xBE', '\a', '\x10', '\x2', 
		'\x2', '\xBE', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', 
		'\x18', '\x2', '\x2', '\xC0', '\xC1', '\a', '\f', '\x2', '\x2', '\xC1', 
		'\xC2', '\a', '\x3', '\x2', '\x2', '\xC2', '\xC3', '\a', '\x31', '\x2', 
		'\x2', '\xC3', '\xC4', '\a', '\x12', '\x2', '\x2', '\xC4', '\xC5', '\x5', 
		'\x18', '\r', '\x2', '\xC5', '\xC6', '\a', '\x11', '\x2', '\x2', '\xC6', 
		'\xC7', '\x5', '\x1A', '\xE', '\x2', '\xC7', '\xCC', '\a', '\x11', '\x2', 
		'\x2', '\xC8', '\xC9', '\a', '\x31', '\x2', '\x2', '\xC9', '\xCD', '\a', 
		'\x14', '\x2', '\x2', '\xCA', '\xCB', '\a', '\x31', '\x2', '\x2', '\xCB', 
		'\xCD', '\a', '\x15', '\x2', '\x2', '\xCC', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCF', '\a', '\xE', '\x2', '\x2', '\xCF', 
		'\xD0', '\a', '\xF', '\x2', '\x2', '\xD0', '\xD1', '\x5', '\x4', '\x3', 
		'\x2', '\xD1', '\xD2', '\a', '\x10', '\x2', '\x2', '\xD2', '\xEB', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD4', '\a', '\x31', '\x2', '\x2', '\xD4', 
		'\xDD', '\a', '\f', '\x2', '\x2', '\xD5', '\xDA', '\a', '\x31', '\x2', 
		'\x2', '\xD6', '\xD7', '\a', '\r', '\x2', '\x2', '\xD7', '\xD9', '\a', 
		'\x31', '\x2', '\x2', '\xD8', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xDA', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xD5', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xEB', '\a', 
		'\xE', '\x2', '\x2', '\xE0', '\xE4', '\x5', '\x12', '\n', '\x2', '\xE1', 
		'\xE3', '\x5', '\x14', '\v', '\x2', '\xE2', '\xE1', '\x3', '\x2', '\x2', 
		'\x2', '\xE3', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE2', '\x3', 
		'\x2', '\x2', '\x2', '\xE4', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE4', '\x3', '\x2', '\x2', 
		'\x2', '\xE7', '\xE9', '\x5', '\x16', '\f', '\x2', '\xE8', '\xE7', '\x3', 
		'\x2', '\x2', '\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE9', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', '\xEA', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '\x8D', '\x3', '\x2', '\x2', '\x2', '\xEA', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\x94', '\x3', '\x2', '\x2', '\x2', '\xEA', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xA4', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xEA', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xE0', '\x3', 
		'\x2', '\x2', '\x2', '\xEB', '\x11', '\x3', '\x2', '\x2', '\x2', '\xEC', 
		'\xED', '\a', '\x19', '\x2', '\x2', '\xED', '\xEE', '\a', '\f', '\x2', 
		'\x2', '\xEE', '\xEF', '\x5', '\x1A', '\xE', '\x2', '\xEF', '\xF0', '\a', 
		'\xE', '\x2', '\x2', '\xF0', '\xF1', '\a', '\xF', '\x2', '\x2', '\xF1', 
		'\xF2', '\x5', '\x4', '\x3', '\x2', '\xF2', '\xF3', '\a', '\x10', '\x2', 
		'\x2', '\xF3', '\x13', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF5', '\a', 
		'\x1A', '\x2', '\x2', '\xF5', '\xF6', '\a', '\f', '\x2', '\x2', '\xF6', 
		'\xF7', '\x5', '\x1A', '\xE', '\x2', '\xF7', '\xF8', '\a', '\xE', '\x2', 
		'\x2', '\xF8', '\xF9', '\a', '\xF', '\x2', '\x2', '\xF9', '\xFA', '\x5', 
		'\x4', '\x3', '\x2', '\xFA', '\xFB', '\a', '\x10', '\x2', '\x2', '\xFB', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xFD', '\a', '\x1B', '\x2', 
		'\x2', '\xFD', '\xFE', '\a', '\xF', '\x2', '\x2', '\xFE', '\xFF', '\x5', 
		'\x4', '\x3', '\x2', '\xFF', '\x100', '\a', '\x10', '\x2', '\x2', '\x100', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x101', '\x102', '\b', '\r', '\x1', 
		'\x2', '\x102', '\x103', '\a', '\f', '\x2', '\x2', '\x103', '\x104', '\x5', 
		'\x18', '\r', '\x2', '\x104', '\x105', '\a', '\xE', '\x2', '\x2', '\x105', 
		'\x11E', '\x3', '\x2', '\x2', '\x2', '\x106', '\x107', '\a', '\x1C', '\x2', 
		'\x2', '\x107', '\x11E', '\x5', '\x18', '\r', '\x11', '\x108', '\x10C', 
		'\a', '\x31', '\x2', '\x2', '\x109', '\x10A', '\a', '\a', '\x2', '\x2', 
		'\x10A', '\x10B', '\t', '\x4', '\x2', '\x2', '\x10B', '\x10D', '\a', '\b', 
		'\x2', '\x2', '\x10C', '\x109', '\x3', '\x2', '\x2', '\x2', '\x10C', '\x10D', 
		'\x3', '\x2', '\x2', '\x2', '\x10D', '\x111', '\x3', '\x2', '\x2', '\x2', 
		'\x10E', '\x10F', '\a', '\a', '\x2', '\x2', '\x10F', '\x110', '\t', '\x4', 
		'\x2', '\x2', '\x110', '\x112', '\a', '\b', '\x2', '\x2', '\x111', '\x10E', 
		'\x3', '\x2', '\x2', '\x2', '\x111', '\x112', '\x3', '\x2', '\x2', '\x2', 
		'\x112', '\x11E', '\x3', '\x2', '\x2', '\x2', '\x113', '\x114', '\a', 
		'\x31', '\x2', '\x2', '\x114', '\x11E', '\a', '$', '\x2', '\x2', '\x115', 
		'\x116', '\a', '\x31', '\x2', '\x2', '\x116', '\x11E', '\a', '%', '\x2', 
		'\x2', '\x117', '\x118', '\a', '\x31', '\x2', '\x2', '\x118', '\x11E', 
		'\a', '&', '\x2', '\x2', '\x119', '\x11A', '\a', '\"', '\x2', '\x2', '\x11A', 
		'\x11E', '\x5', '\x18', '\r', '\x5', '\x11B', '\x11E', '\a', '/', '\x2', 
		'\x2', '\x11C', '\x11E', '\a', '\x30', '\x2', '\x2', '\x11D', '\x101', 
		'\x3', '\x2', '\x2', '\x2', '\x11D', '\x106', '\x3', '\x2', '\x2', '\x2', 
		'\x11D', '\x108', '\x3', '\x2', '\x2', '\x2', '\x11D', '\x113', '\x3', 
		'\x2', '\x2', '\x2', '\x11D', '\x115', '\x3', '\x2', '\x2', '\x2', '\x11D', 
		'\x117', '\x3', '\x2', '\x2', '\x2', '\x11D', '\x119', '\x3', '\x2', '\x2', 
		'\x2', '\x11D', '\x11B', '\x3', '\x2', '\x2', '\x2', '\x11D', '\x11C', 
		'\x3', '\x2', '\x2', '\x2', '\x11E', '\x136', '\x3', '\x2', '\x2', '\x2', 
		'\x11F', '\x120', '\f', '\x10', '\x2', '\x2', '\x120', '\x121', '\a', 
		'\x1D', '\x2', '\x2', '\x121', '\x135', '\x5', '\x18', '\r', '\x11', '\x122', 
		'\x123', '\f', '\xF', '\x2', '\x2', '\x123', '\x124', '\a', '\x1E', '\x2', 
		'\x2', '\x124', '\x135', '\x5', '\x18', '\r', '\x10', '\x125', '\x126', 
		'\f', '\xE', '\x2', '\x2', '\x126', '\x127', '\a', '\x1F', '\x2', '\x2', 
		'\x127', '\x135', '\x5', '\x18', '\r', '\xF', '\x128', '\x129', '\f', 
		'\r', '\x2', '\x2', '\x129', '\x12A', '\a', ' ', '\x2', '\x2', '\x12A', 
		'\x135', '\x5', '\x18', '\r', '\xE', '\x12B', '\x12C', '\f', '\f', '\x2', 
		'\x2', '\x12C', '\x12D', '\a', '!', '\x2', '\x2', '\x12D', '\x135', '\x5', 
		'\x18', '\r', '\r', '\x12E', '\x12F', '\f', '\v', '\x2', '\x2', '\x12F', 
		'\x130', '\a', '\"', '\x2', '\x2', '\x130', '\x135', '\x5', '\x18', '\r', 
		'\f', '\x131', '\x132', '\f', '\n', '\x2', '\x2', '\x132', '\x133', '\a', 
		'#', '\x2', '\x2', '\x133', '\x135', '\x5', '\x18', '\r', '\v', '\x134', 
		'\x11F', '\x3', '\x2', '\x2', '\x2', '\x134', '\x122', '\x3', '\x2', '\x2', 
		'\x2', '\x134', '\x125', '\x3', '\x2', '\x2', '\x2', '\x134', '\x128', 
		'\x3', '\x2', '\x2', '\x2', '\x134', '\x12B', '\x3', '\x2', '\x2', '\x2', 
		'\x134', '\x12E', '\x3', '\x2', '\x2', '\x2', '\x134', '\x131', '\x3', 
		'\x2', '\x2', '\x2', '\x135', '\x138', '\x3', '\x2', '\x2', '\x2', '\x136', 
		'\x134', '\x3', '\x2', '\x2', '\x2', '\x136', '\x137', '\x3', '\x2', '\x2', 
		'\x2', '\x137', '\x19', '\x3', '\x2', '\x2', '\x2', '\x138', '\x136', 
		'\x3', '\x2', '\x2', '\x2', '\x139', '\x13A', '\b', '\xE', '\x1', '\x2', 
		'\x13A', '\x13D', '\t', '\x5', '\x2', '\x2', '\x13B', '\x13D', '\x5', 
		'\x18', '\r', '\x2', '\x13C', '\x139', '\x3', '\x2', '\x2', '\x2', '\x13C', 
		'\x13B', '\x3', '\x2', '\x2', '\x2', '\x13D', '\x152', '\x3', '\x2', '\x2', 
		'\x2', '\x13E', '\x13F', '\f', '\n', '\x2', '\x2', '\x13F', '\x140', '\a', 
		'\'', '\x2', '\x2', '\x140', '\x151', '\x5', '\x1A', '\xE', '\v', '\x141', 
		'\x142', '\f', '\t', '\x2', '\x2', '\x142', '\x143', '\a', '(', '\x2', 
		'\x2', '\x143', '\x151', '\x5', '\x1A', '\xE', '\n', '\x144', '\x145', 
		'\f', '\b', '\x2', '\x2', '\x145', '\x146', '\a', ')', '\x2', '\x2', '\x146', 
		'\x151', '\x5', '\x1A', '\xE', '\t', '\x147', '\x148', '\f', '\a', '\x2', 
		'\x2', '\x148', '\x149', '\a', '*', '\x2', '\x2', '\x149', '\x151', '\x5', 
		'\x1A', '\xE', '\b', '\x14A', '\x14B', '\f', '\x6', '\x2', '\x2', '\x14B', 
		'\x14C', '\a', '+', '\x2', '\x2', '\x14C', '\x151', '\x5', '\x1A', '\xE', 
		'\a', '\x14D', '\x14E', '\f', '\x5', '\x2', '\x2', '\x14E', '\x14F', '\a', 
		',', '\x2', '\x2', '\x14F', '\x151', '\x5', '\x1A', '\xE', '\x6', '\x150', 
		'\x13E', '\x3', '\x2', '\x2', '\x2', '\x150', '\x141', '\x3', '\x2', '\x2', 
		'\x2', '\x150', '\x144', '\x3', '\x2', '\x2', '\x2', '\x150', '\x147', 
		'\x3', '\x2', '\x2', '\x2', '\x150', '\x14A', '\x3', '\x2', '\x2', '\x2', 
		'\x150', '\x14D', '\x3', '\x2', '\x2', '\x2', '\x151', '\x154', '\x3', 
		'\x2', '\x2', '\x2', '\x152', '\x150', '\x3', '\x2', '\x2', '\x2', '\x152', 
		'\x153', '\x3', '\x2', '\x2', '\x2', '\x153', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x154', '\x152', '\x3', '\x2', '\x2', '\x2', '\x1D', '!', '#', 
		'.', '\x33', '\x39', '>', '\x42', '\x46', 'T', 'W', 'j', '\x82', '\x88', 
		'\xCC', '\xDA', '\xDD', '\xE4', '\xE8', '\xEA', '\x10C', '\x111', '\x11D', 
		'\x134', '\x136', '\x13C', '\x150', '\x152',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
