//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\noobs\OneDrive\Documents\GitHub\P4-Emotional-Damage\Compiler\folder\test.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class testParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, Inum=29, Fnum=30, Dnum=31, String=32, 
		ID=33, WHITESPACE=34, NEWLINE=35;
	public const int
		RULE_prog = 0, RULE_stmts = 1, RULE_stmt = 2, RULE_assignment = 3, RULE_exprs = 4, 
		RULE_expr = 5, RULE_selective = 6, RULE_iterative = 7, RULE_bexpr = 8, 
		RULE_print = 9, RULE_dummy = 10, RULE_val = 11, RULE_valtype = 12, RULE_num = 13;
	public static readonly string[] ruleNames = {
		"prog", "stmts", "stmt", "assignment", "exprs", "expr", "selective", "iterative", 
		"bexpr", "print", "dummy", "val", "valtype", "num"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'='", "','", "'('", "')'", "'sqrt'", "'%'", "'**'", "'*'", 
		"'/'", "'+'", "'-'", "'++'", "'--'", "'if'", "'{'", "'}'", "'elif'", "'else'", 
		"'for'", "'>'", "'<'", "'!'", "'Print'", "'dummy'", "'int'", "'float'", 
		"'double'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "Inum", "Fnum", "Dnum", "String", "ID", 
		"WHITESPACE", "NEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "test.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static testParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public testParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public testParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(testParser.Eof, 0); }
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28; stmts();
			State = 29; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtsContext : ParserRuleContext {
		public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public StmtsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmts; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmts(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtsContext stmts() {
		StmtsContext _localctx = new StmtsContext(Context, State);
		EnterRule(_localctx, 2, RULE_stmts);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__23) | (1L << T__24) | (1L << T__25) | (1L << T__26) | (1L << T__27) | (1L << ID))) != 0)) {
				{
				State = 31; stmt();
				State = 32; stmts();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		public DummyContext dummy() {
			return GetRuleContext<DummyContext>(0);
		}
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 4, RULE_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__25:
			case T__26:
			case T__27:
			case ID:
				{
				State = 36; assignment();
				}
				break;
			case T__23:
				{
				State = 37; print();
				}
				break;
			case T__24:
				{
				State = 38; dummy();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 41; Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(testParser.ID, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ValtypeContext valtype() {
			return GetRuleContext<ValtypeContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 6, RULE_assignment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__25) | (1L << T__26) | (1L << T__27))) != 0)) {
				{
				State = 43; valtype();
				}
			}

			State = 46; Match(ID);
			State = 47; Match(T__1);
			State = 48; expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprsContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ExprsContext exprs() {
			return GetRuleContext<ExprsContext>(0);
		}
		public ExprsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprs; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprsContext exprs() {
		ExprsContext _localctx = new ExprsContext(Context, State);
		EnterRule(_localctx, 8, RULE_exprs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50; expr(0);
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 51; Match(T__2);
				State = 52; exprs();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ValContext val() {
			return GetRuleContext<ValContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				State = 56; Match(T__3);
				State = 57; expr(0);
				State = 58; Match(T__4);
				}
				break;
			case T__5:
				{
				State = 60; Match(T__5);
				State = 61; expr(7);
				}
				break;
			case T__10:
			case T__11:
			case Inum:
			case Fnum:
			case Dnum:
			case ID:
				{
				State = 62; val();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 80;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 78;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
					case 1:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 65;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 66;
						_la = TokenStream.LA(1);
						if ( !(_la==T__6 || _la==T__7) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 67; expr(7);
						}
						break;
					case 2:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 68;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 69;
						_la = TokenStream.LA(1);
						if ( !(_la==T__8 || _la==T__9) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 70; expr(6);
						}
						break;
					case 3:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 71;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 72;
						_la = TokenStream.LA(1);
						if ( !(_la==T__10 || _la==T__11) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 73; expr(5);
						}
						break;
					case 4:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 74;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 75; Match(T__12);
						}
						break;
					case 5:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 76;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 77; Match(T__13);
						}
						break;
					}
					} 
				}
				State = 82;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class SelectiveContext : ParserRuleContext {
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public StmtsContext[] stmts() {
			return GetRuleContexts<StmtsContext>();
		}
		public StmtsContext stmts(int i) {
			return GetRuleContext<StmtsContext>(i);
		}
		public SelectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selective; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectiveContext selective() {
		SelectiveContext _localctx = new SelectiveContext(Context, State);
		EnterRule(_localctx, 12, RULE_selective);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83; Match(T__14);
			State = 84; Match(T__3);
			State = 85; bexpr(0);
			State = 86; Match(T__4);
			State = 87; Match(T__15);
			State = 88; stmts();
			State = 89; Match(T__16);
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__17) {
				{
				{
				State = 90; Match(T__17);
				State = 91; Match(T__3);
				State = 92; bexpr(0);
				State = 93; Match(T__4);
				State = 94; Match(T__15);
				State = 95; stmts();
				State = 96; Match(T__16);
				}
				}
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 108;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__18) {
				{
				State = 103; Match(T__18);
				State = 104; Match(T__15);
				State = 105; stmts();
				State = 106; Match(T__16);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IterativeContext : ParserRuleContext {
		public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public ExprsContext exprs() {
			return GetRuleContext<ExprsContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public IterativeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iterative; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIterative(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IterativeContext iterative() {
		IterativeContext _localctx = new IterativeContext(Context, State);
		EnterRule(_localctx, 14, RULE_iterative);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110; Match(T__19);
			State = 111; Match(T__3);
			State = 112; assignment();
			State = 113; Match(T__0);
			State = 114; bexpr(0);
			State = 115; Match(T__0);
			State = 116; exprs();
			State = 117; Match(T__4);
			State = 118; Match(T__15);
			State = 119; stmts();
			State = 120; Match(T__16);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BexprContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public BexprContext[] bexpr() {
			return GetRuleContexts<BexprContext>();
		}
		public BexprContext bexpr(int i) {
			return GetRuleContext<BexprContext>(i);
		}
		public BexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bexpr; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BexprContext bexpr() {
		return bexpr(0);
	}

	private BexprContext bexpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BexprContext _localctx = new BexprContext(Context, _parentState);
		BexprContext _prevctx = _localctx;
		int _startState = 16;
		EnterRecursionRule(_localctx, 16, RULE_bexpr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 124;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__22) {
					{
					State = 123; Match(T__22);
					}
				}

				State = 126; expr(0);
				}
				break;
			case 2:
				{
				State = 127; Match(T__22);
				State = 128; Match(T__3);
				State = 129; bexpr(0);
				State = 130; Match(T__4);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 146;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 144;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
					case 1:
						{
						_localctx = new BexprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 134;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 135;
						_la = TokenStream.LA(1);
						if ( !(_la==T__20 || _la==T__21) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 137;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if (_la==T__1) {
							{
							State = 136; Match(T__1);
							}
						}

						State = 139; bexpr(5);
						}
						break;
					case 2:
						{
						_localctx = new BexprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_bexpr);
						State = 140;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 141;
						_la = TokenStream.LA(1);
						if ( !(_la==T__1 || _la==T__22) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 142; Match(T__1);
						State = 143; bexpr(4);
						}
						break;
					}
					} 
				}
				State = 148;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode String() { return GetToken(testParser.String, 0); }
		public ITerminalNode NEWLINE() { return GetToken(testParser.NEWLINE, 0); }
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 18, RULE_print);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 149; Match(T__23);
			State = 152;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
			case T__5:
			case T__10:
			case T__11:
			case Inum:
			case Fnum:
			case Dnum:
			case ID:
				{
				State = 150; expr(0);
				}
				break;
			case String:
				{
				State = 151; Match(String);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 155;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NEWLINE) {
				{
				State = 154; Match(NEWLINE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DummyContext : ParserRuleContext {
		public DummyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dummy; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDummy(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DummyContext dummy() {
		DummyContext _localctx = new DummyContext(Context, State);
		EnterRule(_localctx, 20, RULE_dummy);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 157; Match(T__24);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(testParser.ID, 0); }
		public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		public ValContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_val; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVal(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValContext val() {
		ValContext _localctx = new ValContext(Context, State);
		EnterRule(_localctx, 22, RULE_val);
		int _la;
		try {
			State = 167;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 159; Match(ID);
				}
				break;
			case T__10:
			case T__11:
			case Inum:
			case Fnum:
			case Dnum:
				EnterOuterAlt(_localctx, 2);
				{
				State = 164;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__10:
					{
					State = 160; Match(T__10);
					}
					break;
				case T__11:
				case Inum:
				case Fnum:
				case Dnum:
					{
					State = 162;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==T__11) {
						{
						State = 161; Match(T__11);
						}
					}

					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 166; num();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValtypeContext : ParserRuleContext {
		public ValtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_valtype; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValtype(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValtypeContext valtype() {
		ValtypeContext _localctx = new ValtypeContext(Context, State);
		EnterRule(_localctx, 24, RULE_valtype);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__25) | (1L << T__26) | (1L << T__27))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumContext : ParserRuleContext {
		public ITerminalNode Inum() { return GetToken(testParser.Inum, 0); }
		public ITerminalNode Fnum() { return GetToken(testParser.Fnum, 0); }
		public ITerminalNode Dnum() { return GetToken(testParser.Dnum, 0); }
		public NumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ItestVisitor<TResult> typedVisitor = visitor as ItestVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumContext num() {
		NumContext _localctx = new NumContext(Context, State);
		EnterRule(_localctx, 26, RULE_num);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Inum) | (1L << Fnum) | (1L << Dnum))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return expr_sempred((ExprContext)_localctx, predIndex);
		case 8: return bexpr_sempred((BexprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 6);
		case 1: return Precpred(Context, 5);
		case 2: return Precpred(Context, 4);
		case 3: return Precpred(Context, 3);
		case 4: return Precpred(Context, 2);
		}
		return true;
	}
	private bool bexpr_sempred(BexprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 5: return Precpred(Context, 4);
		case 6: return Precpred(Context, 3);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '%', '\xB0', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '%', '\n', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '*', '\n', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x5', '\x5', '/', '\n', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x38', '\n', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x5', '\a', '\x42', '\n', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\a', '\a', 'Q', '\n', '\a', '\f', '\a', '\xE', '\a', 'T', 
		'\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', 
		'\b', '\x65', '\n', '\b', '\f', '\b', '\xE', '\b', 'h', '\v', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', 
		'o', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\x7F', 
		'\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', '\x87', '\n', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', '\x8C', '\n', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\a', '\n', '\x93', '\n', 
		'\n', '\f', '\n', '\xE', '\n', '\x96', '\v', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x5', '\v', '\x9B', '\n', '\v', '\x3', '\v', '\x5', 
		'\v', '\x9E', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x5', '\r', '\xA5', '\n', '\r', '\x5', '\r', '\xA7', 
		'\n', '\r', '\x3', '\r', '\x5', '\r', '\xAA', '\n', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x2', '\x4', 
		'\f', '\x12', '\x10', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x2', '\t', '\x3', '\x2', 
		'\t', '\n', '\x3', '\x2', '\v', '\f', '\x3', '\x2', '\r', '\xE', '\x3', 
		'\x2', '\x17', '\x18', '\x4', '\x2', '\x4', '\x4', '\x19', '\x19', '\x3', 
		'\x2', '\x1C', '\x1E', '\x3', '\x2', '\x1F', '!', '\x2', '\xB9', '\x2', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x4', '$', '\x3', '\x2', '\x2', '\x2', 
		'\x6', ')', '\x3', '\x2', '\x2', '\x2', '\b', '.', '\x3', '\x2', '\x2', 
		'\x2', '\n', '\x34', '\x3', '\x2', '\x2', '\x2', '\f', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\xE', 'U', '\x3', '\x2', '\x2', '\x2', '\x10', 'p', 
		'\x3', '\x2', '\x2', '\x2', '\x12', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '\x97', '\x3', '\x2', '\x2', '\x2', '\x16', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\xA9', '\x3', '\x2', '\x2', '\x2', '\x1A', '\xAB', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\xAD', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '\x1F', '\x5', '\x4', '\x3', '\x2', '\x1F', ' ', '\a', '\x2', 
		'\x2', '\x3', ' ', '\x3', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\x5', 
		'\x6', '\x4', '\x2', '\"', '#', '\x5', '\x4', '\x3', '\x2', '#', '%', 
		'\x3', '\x2', '\x2', '\x2', '$', '!', '\x3', '\x2', '\x2', '\x2', '$', 
		'%', '\x3', '\x2', '\x2', '\x2', '%', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'&', '*', '\x5', '\b', '\x5', '\x2', '\'', '*', '\x5', '\x14', '\v', '\x2', 
		'(', '*', '\x5', '\x16', '\f', '\x2', ')', '&', '\x3', '\x2', '\x2', '\x2', 
		')', '\'', '\x3', '\x2', '\x2', '\x2', ')', '(', '\x3', '\x2', '\x2', 
		'\x2', '*', '+', '\x3', '\x2', '\x2', '\x2', '+', ',', '\a', '\x3', '\x2', 
		'\x2', ',', '\a', '\x3', '\x2', '\x2', '\x2', '-', '/', '\x5', '\x1A', 
		'\xE', '\x2', '.', '-', '\x3', '\x2', '\x2', '\x2', '.', '/', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x30', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', 
		'\a', '#', '\x2', '\x2', '\x31', '\x32', '\a', '\x4', '\x2', '\x2', '\x32', 
		'\x33', '\x5', '\f', '\a', '\x2', '\x33', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x34', '\x37', '\x5', '\f', '\a', '\x2', '\x35', '\x36', '\a', '\x5', 
		'\x2', '\x2', '\x36', '\x38', '\x5', '\n', '\x6', '\x2', '\x37', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\x3', '\x2', '\x2', '\x2', 
		'\x38', '\v', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\b', '\a', '\x1', 
		'\x2', ':', ';', '\a', '\x6', '\x2', '\x2', ';', '<', '\x5', '\f', '\a', 
		'\x2', '<', '=', '\a', '\a', '\x2', '\x2', '=', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '>', '?', '\a', '\b', '\x2', '\x2', '?', '\x42', '\x5', 
		'\f', '\a', '\t', '@', '\x42', '\x5', '\x18', '\r', '\x2', '\x41', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '>', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'@', '\x3', '\x2', '\x2', '\x2', '\x42', 'R', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\f', '\b', '\x2', '\x2', '\x44', '\x45', '\t', '\x2', 
		'\x2', '\x2', '\x45', 'Q', '\x5', '\f', '\a', '\t', '\x46', 'G', '\f', 
		'\a', '\x2', '\x2', 'G', 'H', '\t', '\x3', '\x2', '\x2', 'H', 'Q', '\x5', 
		'\f', '\a', '\b', 'I', 'J', '\f', '\x6', '\x2', '\x2', 'J', 'K', '\t', 
		'\x4', '\x2', '\x2', 'K', 'Q', '\x5', '\f', '\a', '\a', 'L', 'M', '\f', 
		'\x5', '\x2', '\x2', 'M', 'Q', '\a', '\xF', '\x2', '\x2', 'N', 'O', '\f', 
		'\x4', '\x2', '\x2', 'O', 'Q', '\a', '\x10', '\x2', '\x2', 'P', '\x43', 
		'\x3', '\x2', '\x2', '\x2', 'P', '\x46', '\x3', '\x2', '\x2', '\x2', 'P', 
		'I', '\x3', '\x2', '\x2', '\x2', 'P', 'L', '\x3', '\x2', '\x2', '\x2', 
		'P', 'N', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', '\x2', '\x2', 
		'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 
		'S', '\r', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', '\x11', '\x2', '\x2', 'V', 'W', '\a', '\x6', '\x2', 
		'\x2', 'W', 'X', '\x5', '\x12', '\n', '\x2', 'X', 'Y', '\a', '\a', '\x2', 
		'\x2', 'Y', 'Z', '\a', '\x12', '\x2', '\x2', 'Z', '[', '\x5', '\x4', '\x3', 
		'\x2', '[', '\x66', '\a', '\x13', '\x2', '\x2', '\\', ']', '\a', '\x14', 
		'\x2', '\x2', ']', '^', '\a', '\x6', '\x2', '\x2', '^', '_', '\x5', '\x12', 
		'\n', '\x2', '_', '`', '\a', '\a', '\x2', '\x2', '`', '\x61', '\a', '\x12', 
		'\x2', '\x2', '\x61', '\x62', '\x5', '\x4', '\x3', '\x2', '\x62', '\x63', 
		'\a', '\x13', '\x2', '\x2', '\x63', '\x65', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\\', '\x3', '\x2', '\x2', '\x2', '\x65', 'h', '\x3', '\x2', '\x2', 
		'\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'n', '\x3', '\x2', '\x2', '\x2', 'h', '\x66', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '\x15', '\x2', '\x2', 'j', 
		'k', '\a', '\x12', '\x2', '\x2', 'k', 'l', '\x5', '\x4', '\x3', '\x2', 
		'l', 'm', '\a', '\x13', '\x2', '\x2', 'm', 'o', '\x3', '\x2', '\x2', '\x2', 
		'n', 'i', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 
		'o', '\xF', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\x16', '\x2', 
		'\x2', 'q', 'r', '\a', '\x6', '\x2', '\x2', 'r', 's', '\x5', '\b', '\x5', 
		'\x2', 's', 't', '\a', '\x3', '\x2', '\x2', 't', 'u', '\x5', '\x12', '\n', 
		'\x2', 'u', 'v', '\a', '\x3', '\x2', '\x2', 'v', 'w', '\x5', '\n', '\x6', 
		'\x2', 'w', 'x', '\a', '\a', '\x2', '\x2', 'x', 'y', '\a', '\x12', '\x2', 
		'\x2', 'y', 'z', '\x5', '\x4', '\x3', '\x2', 'z', '{', '\a', '\x13', '\x2', 
		'\x2', '{', '\x11', '\x3', '\x2', '\x2', '\x2', '|', '~', '\b', '\n', 
		'\x1', '\x2', '}', '\x7F', '\a', '\x19', '\x2', '\x2', '~', '}', '\x3', 
		'\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '\x80', '\x87', '\x5', '\f', '\a', 
		'\x2', '\x81', '\x82', '\a', '\x19', '\x2', '\x2', '\x82', '\x83', '\a', 
		'\x6', '\x2', '\x2', '\x83', '\x84', '\x5', '\x12', '\n', '\x2', '\x84', 
		'\x85', '\a', '\a', '\x2', '\x2', '\x85', '\x87', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '|', '\x3', '\x2', '\x2', '\x2', '\x86', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x94', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\f', '\x6', '\x2', '\x2', '\x89', '\x8B', '\t', '\x5', '\x2', 
		'\x2', '\x8A', '\x8C', '\a', '\x4', '\x2', '\x2', '\x8B', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x93', '\x5', '\x12', '\n', 
		'\a', '\x8E', '\x8F', '\f', '\x5', '\x2', '\x2', '\x8F', '\x90', '\t', 
		'\x6', '\x2', '\x2', '\x90', '\x91', '\a', '\x4', '\x2', '\x2', '\x91', 
		'\x93', '\x5', '\x12', '\n', '\x6', '\x92', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x93', '\x96', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x92', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x95', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x94', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9A', '\a', 
		'\x1A', '\x2', '\x2', '\x98', '\x9B', '\x5', '\f', '\a', '\x2', '\x99', 
		'\x9B', '\a', '\"', '\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\a', '%', '\x2', '\x2', '\x9D', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x15', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'\x1B', '\x2', '\x2', '\xA0', '\x17', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xAA', '\a', '#', '\x2', '\x2', '\xA2', '\xA7', '\a', '\r', '\x2', '\x2', 
		'\xA3', '\xA5', '\a', '\xE', '\x2', '\x2', '\xA4', '\xA3', '\x3', '\x2', 
		'\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA7', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\xA2', '\x3', '\x2', '\x2', '\x2', 
		'\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', 
		'\x2', '\x2', '\xA8', '\xAA', '\x5', '\x1C', '\xF', '\x2', '\xA9', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\xA9', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\xAA', '\x19', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\t', '\a', 
		'\x2', '\x2', '\xAC', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', 
		'\t', '\b', '\x2', '\x2', '\xAE', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x15', '$', ')', '.', '\x37', '\x41', 'P', 'R', '\x66', 'n', '~', '\x86', 
		'\x8B', '\x92', '\x94', '\x9A', '\x9D', '\xA4', '\xA6', '\xA9',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
